### 2.1.1 Getting Started

In [2]:
import torch # PyTorch library

- n-dimensional array, also known as a tensor
- resembles NumPy's ndarray
- In the one-dimensional case, i.e., when only one axis is needed for the data, a tensor is called a vector.
- With two axes, a tensor is called a matrix.
- With axes, we drop the specialized names and just refer to the object as a -order tensor.

In [3]:
x = torch.arange(12, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [4]:
x.numel()

12

In [5]:
x.shape

torch.Size([12])

In [6]:
X = x.reshape(3, 4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

- Given a tensor of size n and target shape (h, w), we know that w = n/h.
- To automatically infer one component of the shape, we can place a -1 for the shape component that should be inferred automatically.

In [7]:
X = x.reshape(2, -1)
X

tensor([[ 0.,  1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10., 11.]])

In [15]:
X = x.reshape(-1, 4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [9]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [10]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [11]:
torch.randn(3, 4)

tensor([[-1.2275,  0.6558,  0.1522, -0.3274],
        [-0.8812, -2.5618,  0.2345, -0.4983],
        [ 1.8695,  0.0745, -1.6237,  2.7630]])

- We can construct a matrix with a list of lists, where the outermost list corresponds to axis 0, and the inner list corresponds to axis 1.

In [12]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

### 2.1.2 Indexing and Slicing

- As with Python lists, we can access tensor elements by indexing (starting with 0)
- When only one index (or slice) is specified for a k-order tensor, it is applied along axis 0

In [17]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [16]:
X[-1], X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [18]:
X[1, 2] = 17
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5., 17.,  7.],
        [ 8.,  9., 10., 11.]])

- If we want to assign multiple elements the same value, we apply the indexing on the left-hand side of the assignment operation
- For instance, [:2, :] accesses the first and second rows, where : takes all the elements along axis 1 (column)

In [19]:
X[:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

### 2.1.3 Operations

In [20]:
torch.exp(x)

tensor([162754.7969, 162754.7969, 162754.7969, 162754.7969, 162754.7969,
        162754.7969, 162754.7969, 162754.7969,   2980.9580,   8103.0840,
         22026.4648,  59874.1406])

In [21]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

- Rows = axis 0
- Columns = axis 1
- We can concatenate multiple tensors (stacking them end-to-end to form a larger one) by providing a list of tensors and specifying along which axis to concatenate

In [22]:
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [23]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

- Summing all the elements in a tensor yields a tensor with only one element

In [24]:
X.sum()

tensor(66.)

### 2.1.4 Broadcasting

- Elementwise binary operations can still be performed when shapes differ using the broadcasting mechanism
- Broadcasting works in a two-step procedure:
  1. expand one or both arrays by copying elements along axes with length 1 so that after this transformation, the two tensors have the same shape
  2. perform an elementwise operation on the resulting arrays

In [25]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

- Broadcasting produces a larger 3 x 2 matrix by replicating matrix a (3 x 1) along the columns and matrix b (1 x 2) along the rows before adding them elementwise

In [26]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

### 2.1.5 Saving Memory

In [31]:
before = id(Y)
Y = Y + X
id(Y) == before

False

- Memory can be saved by updating variables in place
- We can assign the result of an operation to a previously allocated array Y by using slice notation: Y[:] = expression

In [34]:
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))

id(Z): 128073779650288
id(Z): 128073779650288


- If the value of X is not reused in subsequent computations, we can also use X[:] = X + Y or X += Y to reduce the memory overhead of the operation

In [35]:
before = id(X)
X += Y
id(X) == before

True

### 2.1.6 Conversion to Other Python Objects

In [38]:
A = X.numpy()
B = torch.from_numpy(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

- To convert a size-1 tensor to a Python scalar, we can invoke the item function or Python’s built-in functions

In [39]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

### 2.1.7. Summary

- The tensor class is the main interface for storing and manipulating data in deep learning libraries

### 2.1.8 Exercises

1. Run the code in this section. Change the conditional statement X == Y to X < Y or X > Y, and then see what kind of tensor you can get.

In [40]:
X == Y

tensor([[ True, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [41]:
X < Y

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [42]:
X > Y

tensor([[False,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])

2. Replace the two tensors that operate by element in the broadcasting mechanism with other shapes, e.g., 3-dimensional tensors. Is the result the same as expected?

In [43]:
c = torch.arange(6).reshape((3, 1, 2))
d = torch.arange(8).reshape((4, 2))
c, d

(tensor([[[0, 1]],
 
         [[2, 3]],
 
         [[4, 5]]]),
 tensor([[0, 1],
         [2, 3],
         [4, 5],
         [6, 7]]))

In [44]:
c + d

tensor([[[ 0,  2],
         [ 2,  4],
         [ 4,  6],
         [ 6,  8]],

        [[ 2,  4],
         [ 4,  6],
         [ 6,  8],
         [ 8, 10]],

        [[ 4,  6],
         [ 6,  8],
         [ 8, 10],
         [10, 12]]])